### ISSUE TITLE
lecture slides

### ISSUE THREAD

**Issue by snehashis1997** [lihongguang00/CS4277_Labs#1]
hello, can you pls upload lecture notes here?

**Comment by lihongguang00** [comment]
Hi, the course does not have lecture notes, it only has lecture slides which I can't upload due to intellectual property infringement. You can instead follow the recorded lectures [here](https://www.youtube.com/watch?v=LAHQ_qIzNGU&list=PLxg0CGqViygP47ERvqHw_v7FVnUovJeaz). Cheers
